prefix aida: <https://raw.githubusercontent.com/NextCenturyCorporation/AIDA-Interchange-Format/master/java/src/main/resources/com/ncc/aif/ontologies/InterchangeOntology#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct ?hypothesis
(COUNT(DISTINCT ?event) as ?eventCount)
(COUNT(DISTINCT ?entity) as ?entityCount)
(COUNT(DISTINCT ?relation) as ?relationCount)
{$from}
where {
    aida:Hypothesis ^a ?hypothesis .
    ?event a aida:Event .
    OPTIONAL { ?entity a aida:Entity } .
    OPTIONAL { ?relation a aida:Relation } .
}
group by ?hypothesis {$limit}
