version: "3"
services:
  verdi-ui-restapi:
    hostname: verdi-ui-restapi
    env_file:
      - docker/local/docker.env
    #build:
    #  context: ./
    #  dockerfile: docker/local/verdi-ui-restapi/Dockerfile
    image: darpaaida/aidarestapi:1.0
    ports:
      - "8008:8008"
  verdi-ui-gui:
    hostname: verdi-ui-gui
    env_file:
      - docker/local/docker.env
    image: darpaaida/aidaui:1.0
    #build:
    #  context: ./GUI
    #  dockerfile: ../docker/local/verdi-ui-gui/Dockerfile
    ports:
      - "8081:8081"
  verdi-ui-blazegraph:
    image: darpaaida/blazegraph_data:1.0
    ports:
      - "9999:9999"      
