prefix auicql: <https://www.caci.com/aida-ui/claimquerylist#>

SELECT DISTINCT ?queryListId ?assocaitedClaimQueryId

FROM <https://www.caci.com/aida-ui/claimquerylist>

WHERE
{
	?queryValue ?o ?p ;
	auicql:queryListId "{$queryListId}";
    auicql:queryListId ?queryListId;
    OPTIONAL { ?queryValue auicql:assocaitedClaimQueryId ?assocaitedClaimQueryId } .
}
