prefix auicq: <https://www.caci.com/aida-ui/claimquery#>

DELETE
 { ?queryClaim ?p ?v }
WHERE
  { ?queryClaim auicq:queryId ?queryId .
    FILTER ( ?queryId = "{$queryId}"^^xsd:string )
    ?queryClaim ?p ?v
  };

  